config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  resources :conversations do
    resources :messages
  end
  resources :event_dates do
    resources :guest_lists
    resources :events
  end
  resources :admin_manages do
    resources :users
    resources :events
    resources :organizations
  end
  resources :system_admins do
    resources :users
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :reply_comments do
        resources :events
      end
      resources :comments do
        resources :events
      end
      resources :organizations do
        resources :comments
        resources :events
        resources :members_lists
        resources :users
      end
      resources :reports do
        resources :events
      end
      resources :users do
        resources :events
        resources :system_admins
        resources :mailboxes
        resources :sent_messages
        resources :event_dates
        resources :event_creators
        resources :members_lists
        resources :votes
        resources :organizations
      end
      resources :events do
        resources :guest_lists
        resources :comments
        resources :reports
        resources :users
        resources :event_creators
        resources :organizations
        resources :members_lists
        resources :votes
        resources :reply_comments
      end
      resources :system_admins do
        resources :users
      end
      resources :guest_lists do
        resources :events
        resources :event_dates
        resources :votes
      end
      resources :multimedia do
        resources :events
      end
      resources :reports do
        resources :report_comments
      end
      resources :sent_messages do
        resources :mailboxes
        resources :users
      end
      resources :mailboxes do
        resources :sent_messages
        resources :users
      end
      resources :event_creators do
        resources :events
        resources :users
      end
      resources :members_lists do
        resources :events
        resources :users
        resources :organizations
      end
      resources :votes do
        resources :events
        resources :users
        resources :guest_lists
        resources :event_dates
      end
    end
  end
  resources :events, defaults: { format: :html }
  resources :comments, defaults: { format: :html }
  resources :organizations, defaults: { format: :html }
  resources :system_admins, defaults: { format: :html }
  resources :users, defaults: { format: :html }
  resources :guest_lists, defaults: { format: :html }
  resources :multimedia, defaults: { format: :html }
  resources :event_dates, defaults: { format: :html }
  resources :votes,defaults: { format: :html }
  resources :reports,defaults: { format: :html }
  resources :searches
  resources :terms
  resources :au_ps
  resources :mailboxes,defaults: { format: :html }
  resources :sent_messages,defaults: { format: :html }
  resources :event_creators, defaults: { format: :html }
  resources :members_lists, defaults: { format: :html }
  resources :reply_comments, defaults: { format: :html}
end

app/models/system_admin.rb
class SystemAdmin < ApplicationRecord
  has_one :User
end

app/controllers/system_admins_controller.rb
class SystemAdminsController < ApplicationController
  before_action :set_system_admin, only: [:show, :edit, :update, :destroy]

  # GET /system_admins
  # GET /system_admins.json
  def index
    @get_id = User.where(id: params[:id]).select(:id)
    @user_in = User.where(id: @get_id)
    @guest = GuestList.where(user_id: @get_id).select(:event_id)
    @invitations = Event.where(id: @guest)
    @user_member = MembersList.where(user_id: @get_id).select(:organization_id)
    @user_org = Organization.where(id: @user_member)
  end

  # GET /system_admins/1
  # GET /system_admins/1.json
  def show
    @get_id = User.where(id: params[:id]).select(:id)
    @user_in = User.where(id: @get_id)
    @guest = GuestList.where(user_id: @get_id).select(:event_id)
    @invitations = Event.where(id: @guest)
    @user_member = MembersList.where(user_id: @get_id).select(:organization_id)
    @user_org = Organization.where(id: @user_member)
  end

  # GET /system_admins/new
  def new
    @system_admin = SystemAdmin.new
  end

  # GET /system_admins/1/edit
  def edit
  end

  # POST /system_admins
  # POST /system_admins.json
  def create
    @system_admin = SystemAdmin.new(system_admin_params)

    respond_to do |format|
      if @system_admin.save
        format.html { redirect_to @system_admin, notice: 'System admin was successfully created.' }
        format.json { render :show, status: :created, location: @system_admin }
      else
        format.html { render :new }
        format.json { render json: @system_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /system_admins/1
  # PATCH/PUT /system_admins/1.json
  def update
    respond_to do |format|
      if @system_admin.update(system_admin_params)
        format.html { redirect_to @system_admin, notice: 'System admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @system_admin }
      else
        format.html { render :edit }
        format.json { render json: @system_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_admins/1
  # DELETE /system_admins/1.json
  def destroy
    @system_admin.destroy
    respond_to do |format|
      format.html { redirect_to system_admins_url, notice: 'System admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system_admin
      @system_admin = SystemAdmin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def system_admin_params
      params.fetch(:system_admin, {})
    end
end

app/helpers/system_admins_helper.rb
module SystemAdminsHelper
end

app/views/system_admins/_form.html.erb
<%= form_with(model: system_admin, local: true) do |form| %>
  <% if system_admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(system_admin.errors.count, "error") %> prohibited this system_admin from being saved:</h2>

      <ul>
        <% system_admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/system_admins/edit.html.erb
<h1>Editing System Admin</h1>

<%= render 'form', system_admin: @system_admin %>

<%= link_to 'Show', @system_admin %> |
<%= link_to 'Back', system_admins_path %>

app/views/system_admins/index.html.erb
<%= stylesheet_link_tag 'seedetails-profile'%>

<h2 class="h2details"> <%= User.where(id: current_user.id).select(:full_name).first.full_name %> </h2>
<% unless User.where(id: current_user.id).select(:profile_picture).first.profile_picture.attached? == true%>
  <span class="imageleft1"><%= link_to image_tag("xd.jpeg", width: '300px') %></span>
<% end %>
<% unless User.where(id: current_user.id).select(:profile_picture).first.profile_picture.attached? == false%>
  <span class="imageleft1"><%= link_to image_tag(url_for(User.where(id: current_user.id).select(:profile_picture).first.profile_picture), width: '300px') %></span>
<% end %>
<br/>
<br/>
<br/>
<h4 class="h4detailsp"><%= User.where(id: current_user.id).select(:username).first.username %></h4>
<h4 class="h4details"><%= User.where(id: current_user.id).select(:short_bio).first.short_bio %></h4>
<h4 class="h4details"><%= User.where(id: current_user.id).select(:location).first.location %></h4>
<h4 class="h4details"><%= User.where(id: current_user.id).select(:full_name).first.full_name %></h4>
<h4 class="h4details2"> Email: <%= User.where(id: current_user.id).select(:email).first.email %></h4>
<h4 class="h4details2"> Last Access at: <%= User.where(id: current_user.id).select(:updated_at).first.updated_at %></h4>
<br/>
<aside class="botones">
  <button class="buttondetails"><%= link_to 'Edit', edit_user_path(User.where(id: current_user.id).select(:id).first.id) %></button>
  <button class="back"><%= link_to 'Back', users_path %></button>
</aside>

app/views/system_admins/new.html.erb
<h1>New System Admin</h1>

<%= render 'form', system_admin: @system_admin %>

<%= link_to 'Back', system_admins_path %>

app/views/system_admins/show.html.erb
<%= stylesheet_link_tag 'seedetails-profile'%>

<h2 class="h2details"> <%= User.where(id: @get_id).select(:full_name).first.full_name %> </h2>
<% unless User.where(id: @get_id).select(:profile_picture).first.profile_picture.attached? == true%>
  <span class="imageleft1"><%= link_to image_tag("xd.jpeg", width: '300px') %></span>
<% end %>
<% unless User.where(id: @get_id).select(:profile_picture).first.profile_picture.attached? == false%>
  <span class="imageleft1"><%= link_to image_tag(url_for(User.where(id: @get_id).select(:profile_picture).first.profile_picture), width: '300px') %></span>
<% end %>
</br>
</br>
</br>
</br>
<h4 class="h4detailsp"> Username: <%= User.where(id: @get_id).select(:username).first.username %></h4>
<h4 class="h4details"> Bio: <%= User.where(id: @get_id).select(:short_bio).first.short_bio %></h4>
<h4 class="h4details"> Location: <%= User.where(id: @get_id).select(:location).first.location %></h4>
<h4 class="h4details"> Member since: <%= User.where(id: @get_id).select(:created_at).first.created_at %></h4>
<h4 class="h4details2"> Email: <%= User.where(id: @get_id).select(:email).first.email %></h4>
<h4 class="h4details2"> Last Access at: <%= User.where(id: @get_id).select(:last_active_at).first.last_active_at %></h4>
<%unless User.where(id: @get_id).select(:admin).first.admin == false%>
  <h4 class="h4details2"> User Role: ADMIN </h4>
<%end %>
  <%unless User.where(id: @get_id).select(:admin).first.admin == true %>
    <h4 class="h4details2"> User Role: None </h4>
  <%end %>
<br/>
<aside class="botones">
  <%if User.where(id: @get_id).select(:id).first.id == current_user.id  %>
  <button class="buttondetails"><%= link_to 'Edit', edit_user_path(User.where(id: @get_id).select(:id).first.id) %></button>
  <button class="buttondetails"><%= link_to 'Delete', current_user,  method: :delete, data: { confirm: 'Are you sure?' }%></button>
  <%end %>
</aside>