config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  resources :conversations do
    resources :messages
  end
  resources :event_dates do
    resources :guest_lists
    resources :events
  end
  resources :admin_manages do
    resources :users
    resources :events
    resources :organizations
  end
  resources :system_admins do
    resources :users
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :reply_comments do
        resources :events
      end
      resources :comments do
        resources :events
      end
      resources :organizations do
        resources :comments
        resources :events
        resources :members_lists
        resources :users
      end
      resources :reports do
        resources :events
      end
      resources :users do
        resources :events
        resources :system_admins
        resources :mailboxes
        resources :sent_messages
        resources :event_dates
        resources :event_creators
        resources :members_lists
        resources :votes
        resources :organizations
      end
      resources :events do
        resources :guest_lists
        resources :comments
        resources :reports
        resources :users
        resources :event_creators
        resources :organizations
        resources :members_lists
        resources :votes
        resources :reply_comments
      end
      resources :system_admins do
        resources :users
      end
      resources :guest_lists do
        resources :events
        resources :event_dates
        resources :votes
      end
      resources :multimedia do
        resources :events
      end
      resources :reports do
        resources :report_comments
      end
      resources :sent_messages do
        resources :mailboxes
        resources :users
      end
      resources :mailboxes do
        resources :sent_messages
        resources :users
      end
      resources :event_creators do
        resources :events
        resources :users
      end
      resources :members_lists do
        resources :events
        resources :users
        resources :organizations
      end
      resources :votes do
        resources :events
        resources :users
        resources :guest_lists
        resources :event_dates
      end
    end
  end
  resources :events, defaults: { format: :html }
  resources :comments, defaults: { format: :html }
  resources :organizations, defaults: { format: :html }
  resources :system_admins, defaults: { format: :html }
  resources :users, defaults: { format: :html }
  resources :guest_lists, defaults: { format: :html }
  resources :multimedia, defaults: { format: :html }
  resources :event_dates, defaults: { format: :html }
  resources :votes,defaults: { format: :html }
  resources :reports,defaults: { format: :html }
  resources :searches
  resources :terms
  resources :au_ps
  resources :mailboxes,defaults: { format: :html }
  resources :sent_messages,defaults: { format: :html }
  resources :event_creators, defaults: { format: :html }
  resources :members_lists, defaults: { format: :html }
  resources :reply_comments, defaults: { format: :html}
end

app/models/event_creator.rb
class EventCreator < ApplicationRecord
  has_one :Event
  has_one :User
  validates :user_id, presence:true
  validates :event_id, presence:true

end

app/controllers/event_creators_controller.rb
class EventCreatorsController < ApplicationController
  before_action :set_event_creator, only: [:show, :edit, :update, :destroy]

  # GET /event_creators
  # GET /event_creators.json
  def index
    @user = User.where(id: params[:id]).select(:id)
    @user_events = EventCreator.where(user_id: @user)
    @eventos = Event.where(id: @user_events.select(:event_id))
    @get_id = Event.where(id: params[:id]).select(:id)
    @event_foto = Event.where(id: @get_id)
    @event_name = Event.where(id: @get_id).select(:description)
    @event_date = Event.where(id: @get_id).select(:final_date)
    @event_location = Event.where(id: @get_id).select(:location)
    @event_title = Event.where(id: @get_id).select(:title)
    @id = Event.where(id: @get_id).select(:id)
    @guest = GuestList.where(event_id: @get_id)
  end

  # GET /event_creators/1
  # GET /event_creators/1.json
  def show
    @user = User.where(id: params[:id]).select(:id)
    @user_events = EventCreator.where(user_id: @user)
    @eventos = Event.where(id: @user_events.select(:event_id))
    @get_id = Event.where(id: params[:id]).select(:id)
    @event_foto = Event.where(id: @get_id)
    @event_name = Event.where(id: @get_id).select(:description)
    @event_date = Event.where(id: @get_id).select(:final_date)
    @event_location = Event.where(id: @get_id).select(:location)
    @event_title = Event.where(id: @get_id).select(:title)
    @id = Event.where(id: @get_id).select(:id)
    @guest = GuestList.where(event_id: @get_id)
  end

  # GET /event_creators/new
  def new
    @event_creator = EventCreator.new
  end

  # GET /event_creators/1/edit
  def edit
  end

  # POST /event_creators
  # POST /event_creators.json
  def create
    @event_creator = EventCreator.new(event_creator_params)

    respond_to do |format|
      if @event_creator.save
        format.html { redirect_to @event_creator, notice: 'Event creator was successfully created.' }
        format.json { render :index, status: :created, location: @event_creator }
      else
        format.html { render :new }
        format.json { render json: @event_creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_creators/1
  # PATCH/PUT /event_creators/1.json
  def update
    respond_to do |format|
      if @event_creator.update(event_creator_params)
        format.html { redirect_to @event_creator, notice: 'Event creator was successfully updated.' }
        format.json { render :index, status: :ok, location: @event_creator }
      else
        format.html { render :edit }
        format.json { render json: @event_creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_creators/1
  # DELETE /event_creators/1.json
  def destroy
    @event_creator.destroy
    respond_to do |format|
      format.html { redirect_to event_creators_url, notice: 'Event creator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_creator
      @event_creator = EventCreator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_creator_params
      params.fetch(:event_creator, {}).permit(:id, :event_id, :user_id)
    end
end

app/helpers/event_creators_helper.rb
module EventCreatorsHelper
end

app/views/event_creators/_form.html.erb
<br/>
<h1 class="edith2-1">Link Event to my Profile</h1>
<%= form_with(model: event_creator, local: true) do |form| %>
  <% if event_creator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_creator.errors.count, "error") %> prohibited this event_creator from being saved:</h2>
      <ul>
        <% event_creator.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= form.label :user_id %>
    <br/>
    <%= form.collection_select(:user_id, User.where(id: current_user.id).order(name: :asc), :id, :username, {}, { class: "form-control" }) %>
  </div>
  <div class="actions">
    <%= form.label :event_id %>
    <br/>
    <%unless Organization.where(id: MembersList.where(user_id: current_user.id).select(:organization_id)) != nil %>
    <%= form.collection_select(:event_id, Event.all.order(name: :asc), :id, :title, {}, { class: "form-control" }) %>
    <%end %>
    <%unless Organization.where(id: MembersList.where(user_id: current_user.id).select(:organization_id)) == nil %>
      <%= form.collection_select(:event_id, Event.where(organization_id: nil).order(name: :asc), :id, :title, {}, { class: "form-control" }) %>
    <%end %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_creators/edit.html.erb
<h1>Editing Event Creator</h1>

<%= render 'form', event_creator: @event_creator %>

<%= link_to 'Show', @event_creator %> |
<%= link_to 'Back', event_creators_path %>

app/views/event_creators/index.html.erb
<%= stylesheet_link_tag 'event'%>
<% unless user_signed_in? == false %>
<h3 class="h3-event"> User: <%=User.where(id: current_user.id).select(:full_name).first.full_name%> </h3>
<aside class="aside-event">
  <button class="btn success-1" ><%= link_to 'New Event', new_event_path %></button>
  <button class="btn11 success-1"><%=link_to "Add Event Date", new_event_date_path %></button>
  <button class="btn11 info-1" ><%= link_to 'Configure Event Dates', event_dates_url %></button>
  <br/>
</aside>

<br/>
<br/>
<h2>Created Events</h2>
<% Event.where(id: EventCreator.where(user_id: current_user.id).select(:event_id)).each do |x| %>
  <div class="divorganization">
    <% unless x.banner_picture.attached? == true%>
      <span class="imageleft"><%= link_to image_tag("xd.jpeg") %></span>
    <% end %>
    <% unless x.banner_picture.attached?  == false%>
      <span class="imageleft"><%= link_to image_tag(url_for(x.banner_picture)) %></span>
    <% end %>
    <h4 class="organizationh4-1p"><%= x.title %></h4>
    <h4 class="organizationh4-1"><%= x.description %></h4>
    <h4 class="organizationh4-1"><%= x.location %></h4>
    <h4 class="organizationh4-1"><%= x.final_date %></h4>
    <button class="btn success"><%= link_to 'Event Page', event_path(x) %></button>
    <button class="btn info"><%= link_to 'Guest List', guest_list_path(x) %></button>
    <button class="btn warning"><%= link_to 'Edit', edit_event_path(x) %></button>
    <button class="btn danger"><%= link_to 'Delete', event_path(x), method: :delete, data: { confirm: 'Are you sure?' } %></button>
  </div>
<% end %>
<% end %>

<% unless admin_signed_in? == false %>
  <% Event.all.each do |x| %>
    <div class="divprofile">
      <% unless x.banner_picture.attached? == true%>
        <h4 class="imageleft"><%= link_to image_tag("xd.jpeg", width: '300px') %></h4>
      <% end %>
      <% unless x.banner_picture.attached?  == false%>
        <h4 class="imageleft"><%= link_to image_tag(url_for(x.banner_picture), width: '300px') %></h4>
      <% end %>
      <h4 class="organizationh4-1p"><%= x.title %></h4>
      <h4 class="organizationh4-1"><%= x.description %></h4>
      <h4 class="organizationh4-1"><%= x.location %></h4>
      <h4 class="organizationh4-1"><%= x.final_date %></h4>
      <button class="btn success"><%= link_to 'See Event Page', event_path(x) %></button>
      <button class="btn warning"><%= link_to 'Edit', edit_event_path(x) %></button>
      <button class="btn info"><%= link_to 'See More', guest_list_path(x) %></button>
      <button class="btn danger"><%= link_to 'Delete', x, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    </div>
  <% end %>
<% end %>

app/views/event_creators/new.html.erb
<%= render 'form', event_creator: @event_creator %>

app/views/event_creators/show.html.erb
<%= stylesheet_link_tag 'event'%>
<h3 class="h3-event"> User: <%=User.where(id: current_user.id).select(:full_name).first.full_name%> </h3>
<aside class="aside-event">
  <button class="btn success-1" ><%= link_to 'New Event', new_event_path %></button>
  <button class="btn11 success-1"><%=link_to "Add Event Date", new_event_date_path(Event.where(id: @get_id).first.id) %></button>
  <button class="btn11 info-1" ><%= link_to 'Configure Event Dates', event_dates_url %></button>
  <br/>
</aside>

<h2>Created Events</h2>
<% Event.where(id: EventCreator.where(user_id: current_user.id).select(:event_id)).each do |x| %>
  <div class="divorganization">
    <% unless x.banner_picture.attached? == true%>
      <span class="imageleft"><%= link_to image_tag("xd.jpeg") %></span>
    <% end %>
    <% unless x.banner_picture.attached?  == false%>
      <span class="imageleft"><%= link_to image_tag(url_for(x.banner_picture)) %></span>
    <% end %>
    <h4 class="organizationh4-1p"><%= x.title %></h4>
    <h4 class="organizationh4-1"><%= x.description %></h4>
    <h4 class="organizationh4-1"><%= x.location %></h4>
    <h4 class="organizationh4-1"><%= x.final_date %></h4>
    <button class="btn success"><%= link_to 'See Event Page', event_path(x) %></button>
    <button class="btn warning"><%= link_to 'Edit', edit_event_path(x) %></button>
    <button class="btn info"><%= link_to 'See More', guest_list_path(x) %></button>
    <button class="btn danger"><%= link_to 'Delete', x, method: :destroy, data: { confirm: 'Are you sure?' } %></button>
  </div>
<% end %>