config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  resources :conversations do
    resources :messages
  end
  resources :event_dates do
    resources :guest_lists
    resources :events
  end
  resources :admin_manages do
    resources :users
    resources :events
    resources :organizations
  end
  resources :system_admins do
    resources :users
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :reply_comments do
        resources :events
      end
      resources :comments do
        resources :events
      end
      resources :organizations do
        resources :comments
        resources :events
        resources :members_lists
        resources :users
      end
      resources :reports do
        resources :events
      end
      resources :users do
        resources :events
        resources :system_admins
        resources :mailboxes
        resources :sent_messages
        resources :event_dates
        resources :event_creators
        resources :members_lists
        resources :votes
        resources :organizations
      end
      resources :events do
        resources :guest_lists
        resources :comments
        resources :reports
        resources :users
        resources :event_creators
        resources :organizations
        resources :members_lists
        resources :votes
        resources :reply_comments
      end
      resources :system_admins do
        resources :users
      end
      resources :guest_lists do
        resources :events
        resources :event_dates
        resources :votes
      end
      resources :multimedia do
        resources :events
      end
      resources :reports do
        resources :report_comments
      end
      resources :sent_messages do
        resources :mailboxes
        resources :users
      end
      resources :mailboxes do
        resources :sent_messages
        resources :users
      end
      resources :event_creators do
        resources :events
        resources :users
      end
      resources :members_lists do
        resources :events
        resources :users
        resources :organizations
      end
      resources :votes do
        resources :events
        resources :users
        resources :guest_lists
        resources :event_dates
      end
    end
  end
  resources :events, defaults: { format: :html }
  resources :comments, defaults: { format: :html }
  resources :organizations, defaults: { format: :html }
  resources :system_admins, defaults: { format: :html }
  resources :users, defaults: { format: :html }
  resources :guest_lists, defaults: { format: :html }
  resources :multimedia, defaults: { format: :html }
  resources :event_dates, defaults: { format: :html }
  resources :votes,defaults: { format: :html }
  resources :reports,defaults: { format: :html }
  resources :searches
  resources :terms
  resources :au_ps
  resources :mailboxes,defaults: { format: :html }
  resources :sent_messages,defaults: { format: :html }
  resources :event_creators, defaults: { format: :html }
  resources :members_lists, defaults: { format: :html }
  resources :reply_comments, defaults: { format: :html}
end

app/models/event_date.rb
class EventDate < ApplicationRecord
  has_one :Event
  validates :event_id, presence:true
  validates :date, presence:true
end

app/controllers/event_dates_controller.rb
class EventDatesController < ApplicationController
  before_action :set_event_date, only: [:show, :edit, :update, :destroy]

  # GET /event_dates
  # GET /event_dates.json
  def index
    @get_id = Event.where(id: params[:id]).select(:id)
    @event_dates = EventDate.where(event_id: @get_id)
    @dates_to_choose = EventDate.where(event_id: @get_id).select(:date)
  end

  # GET /event_dates/1
  # GET /event_dates/1.json
  def show
    @get_id = Event.where(id: params[:id]).select(:id)
    @event_dates = EventDate.where(event_id: @get_id)
    @dates_to_choose = EventDate.where(event_id: @get_id).select(:date)
  end

  # GET /event_dates/new
  def new
    @event_date = EventDate.new
  end

  # GET /event_dates/1/edit
  def edit
  end

  # POST /event_dates
  # POST /event_dates.json
  def create
    @event_date = EventDate.new(event_date_params)
    respond_to do |format|
      if @event_date.save
        format.html { redirect_to event_dates_url, notice: 'Event date was successfully created.' }
        format.json { render root_path, status: :created, location: @event_date }
      else
        format.html { render :new }
        format.json { render json: @event_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_dates/1
  # PATCH/PUT /event_dates/1.json
  def update
    respond_to do |format|
      if @event_date.update(event_date_params)
        format.html { redirect_to event_dates_url, notice: 'Event date was successfully updated.' }
        format.json { render root_path, status: :ok, location: @event_date }
      else
        format.html { render :edit }
        format.json { render json: @event_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_dates/1
  # DELETE /event_dates/1.json
  def destroy
    @event_date.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path, notice: 'Event date was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_date
      @event_date = EventDate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_date_params
      params.fetch(:event_date, {}).permit(:id, :date , :event_id)
    end
end

app/helpers/event_dates_helper.rb
module EventDatesHelper
end

app/views/event_dates/_form.html.erb
<%= form_with(model: event_date, local: true) do |form| %>
  <% if event_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_date.errors.count, "error") %> prohibited this event_date from being saved:</h2>

      <ul>
        <% event_date.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_dates/edit.html.erb
<div class="row ml-0 mt-3">
  <h2 class="edith2">Edit the Event Dates</h2>
</div>
<div class="div-2">
<%= form_with model: @event_date, local: true do |form| %>
  <div class="div-edit">
    <%= form.label :date %>
    <br/>
    <%= form.datetime_local_field :date %>
  </div>
  <div class="div-edit">
    <%= form.submit "Update", class: ["btn"] %>
  </div>
<%end %>
</div>
<button class="btn11 info-1" ><%= link_to 'Back', :back %></button>

app/views/event_dates/index.html.erb
<%= stylesheet_link_tag 'dates'%>
<br/>
<h1 class="dates"> >> Dates for the Guest to Vote << </h1>
<br/>
<% Event.where(id: EventCreator.where(user_id: current_user.id).select(:event_id)).each do |x| %>
  <h1 class="dates1">Dates to Vote of the "<%= x.title %>" Event:</h1>
  <div class="datesbotones">
    <button class="btndate1 "><%= link_to 'New Date', new_event_date_path %></button>
    <button class="btndate1 "><%= link_to 'See Event Page', event_path(x) %></button>
    <button class="btndate1"><%= link_to 'Edit Event', edit_event_path(x) %></button>
    <button class="btndate1"><%= link_to 'Delete Event', x, method: :delete, data: { confirm: 'Are you sure?' } %></button>
  </div>
  <br/>
  <% EventDate.where(event_id: x.id).each do |x| %>
    <%if x.date != "1000-01-01 00:00:00" %>
    <div class="divdate">
      <h4 class="h4date">Date: <%= x.date %></h4>
      <br/>
      <button class="btndate "><%= link_to 'Edit', edit_event_date_path(x) %></button>
      <button class="btndate "><%= link_to 'Delete', x, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    </div>
    <br/>
    <br/>
    <% end %>
  <% end %>
<% end %>

app/views/event_dates/new.html.erb
<div class="row ml-0 mt-3">
  <h2 class="edith2"> New Event date</h2>
</div>
<div class="div-2">
  <%= form_with model: @event_date, local: true do |form| %>
    <div class="div-edit">
      <%= form.label :date %>
      <br/>
      <%= form.datetime_local_field :date %>
    </div>
    <div class="div-edit">
      <%= form.label :event_id %>
      <br/>
      <%= form.collection_select(:event_id, Event.where(id: EventCreator.where(user_id: current_user.id).select(:event_id)).order(name: :asc), :id, :title, {}, { class: "form-control" }) %>
    </div>
    <div class="div-edit">
      <%= form.submit "Create", class: ["btn"] %>
    </div>
  <%end %>
</div>
<button class="btn11 info-1" ><%= link_to 'Back', :back %></button>

app/views/event_dates/show.html.erb
<%= stylesheet_link_tag 'event-comments'%>
<br/>
<aside class="aside-comment">
  <button class="btn11 success-1" ><%= link_to 'Back', _back_url %></button>
</aside>
<br/>
<br/>

<h2>Dates: "<%= Event.where(id: @get_id).select(:title).first.title %>" Event:</h2>
<br/>
<% @event_dates.each do |x| %>
  <div>
    <h3 class="User-11"><%= x.date %></h3>
    <button class="btn11 danger2"><%= link_to 'Edit', edit_event_date_path(x)%></button>
    <button class="btn11 danger2"><%= link_to 'Delete', x,  method: :delete, data: { confirm: 'Are you sure?' }%></button>
  </div>
<% end %>