config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  resources :conversations do
    resources :messages
  end
  resources :event_dates do
    resources :guest_lists
    resources :events
  end
  resources :admin_manages do
    resources :users
    resources :events
    resources :organizations
  end
  resources :system_admins do
    resources :users
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :reply_comments do
        resources :events
      end
      resources :comments do
        resources :events
      end
      resources :organizations do
        resources :comments
        resources :events
        resources :members_lists
        resources :users
      end
      resources :reports do
        resources :events
      end
      resources :users do
        resources :events
        resources :system_admins
        resources :mailboxes
        resources :sent_messages
        resources :event_dates
        resources :event_creators
        resources :members_lists
        resources :votes
        resources :organizations
      end
      resources :events do
        resources :guest_lists
        resources :comments
        resources :reports
        resources :users
        resources :event_creators
        resources :organizations
        resources :members_lists
        resources :votes
        resources :reply_comments
      end
      resources :system_admins do
        resources :users
      end
      resources :guest_lists do
        resources :events
        resources :event_dates
        resources :votes
      end
      resources :multimedia do
        resources :events
      end
      resources :reports do
        resources :report_comments
      end
      resources :sent_messages do
        resources :mailboxes
        resources :users
      end
      resources :mailboxes do
        resources :sent_messages
        resources :users
      end
      resources :event_creators do
        resources :events
        resources :users
      end
      resources :members_lists do
        resources :events
        resources :users
        resources :organizations
      end
      resources :votes do
        resources :events
        resources :users
        resources :guest_lists
        resources :event_dates
      end
    end
  end
  resources :events, defaults: { format: :html }
  resources :comments, defaults: { format: :html }
  resources :organizations, defaults: { format: :html }
  resources :system_admins, defaults: { format: :html }
  resources :users, defaults: { format: :html }
  resources :guest_lists, defaults: { format: :html }
  resources :multimedia, defaults: { format: :html }
  resources :event_dates, defaults: { format: :html }
  resources :votes,defaults: { format: :html }
  resources :reports,defaults: { format: :html }
  resources :searches
  resources :terms
  resources :au_ps
  resources :mailboxes,defaults: { format: :html }
  resources :sent_messages,defaults: { format: :html }
  resources :event_creators, defaults: { format: :html }
  resources :members_lists, defaults: { format: :html }
  resources :reply_comments, defaults: { format: :html}
end

app/controllers/admin_manages_controller.rb
class AdminManagesController < ApplicationController
  before_action :set_admin_manage, only: [:show, :edit, :update, :destroy]

  # GET /admin_manages
  # GET /admin_manages.json
  def index
    @todos_usuarios = User.all
    @todos_eventos = Event.all
    @todos_organizaciones = Organization.all
  end

  # GET /admin_manages/1
  # GET /admin_manages/1.json
  def show
  end

  # GET /admin_manages/new
  def new
    @admin_manage = AdminManage.new
  end

  # GET /admin_manages/1/edit
  def edit
  end

  # POST /admin_manages
  # POST /admin_manages.json
  def create
    @admin_manage = AdminManage.new(admin_manage_params)

    respond_to do |format|
      if @admin_manage.save
        format.html { redirect_to @admin_manage, notice: 'Admin manage was successfully created.' }
        format.json { render :show, status: :created, location: @admin_manage }
      else
        format.html { render :new }
        format.json { render json: @admin_manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_manages/1
  # PATCH/PUT /admin_manages/1.json
  def update
    respond_to do |format|
      if @admin_manage.update(admin_manage_params)
        format.html { redirect_to @admin_manage, notice: 'Admin manage was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_manage }
      else
        format.html { render :edit }
        format.json { render json: @admin_manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_manages/1
  # DELETE /admin_manages/1.json
  def destroy
    @admin_manage.destroy
    respond_to do |format|
      format.html { redirect_to admin_manages_url, notice: 'Admin manage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_manage
      @admin_manage = AdminManage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_manage_params
      params.fetch(:admin_manage, {})
    end
end

app/helpers/admin_manages_helper.rb
module AdminManagesHelper
end

app/views/admin_manages/_form.html.erb
<%= form_with(model: admin_manage, local: true) do |form| %>
  <% if admin_manage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_manage.errors.count, "error") %> prohibited this admin_manage from being saved:</h2>

      <ul>
        <% admin_manage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_manages/edit.html.erb
<h1>Editing Admin Manage</h1>

<%= render 'form', admin_manage: @admin_manage %>

<%= link_to 'Show', @admin_manage %> |
<%= link_to 'Back', admin_manages_path %>

app/views/admin_manages/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="h2profile2">Admin Manages</h1>
<h2 class="h2profile2">  Manage Users: </h2>

<% @todos_usuarios.each do |x| %>
  <div class="divprofile">
    <% unless x.profile_picture.attached? == true%>
      <h4 class="imageleft"><%= link_to image_tag("xd.jpeg", width: '300px') %></h4>
    <% end %>
    <% unless x.profile_picture.attached?  == false%>
      <h4 class="imageleft"><%= link_to image_tag(url_for(x.profile_picture), width: '300px') %></h4>
    <% end %>
    <h4 class="h4profilep"><%= x.username %></h4>
    <h4 class="h4profile"><%= x.full_name %></h4>
    <h4 class="h4profile"><%= x.location %></h4>
    <h4 class="h4profile"><%= x.short_bio %></h4>
    <button class="btn info"><%= link_to 'View', user_path(x)  %></button>
    <button class="btn warning"><%= link_to 'Edit', edit_user_path(x)  %></button>

    <button class="btn danger"><%= link_to 'Delete', x, method: :delete, data: { confirm: 'Are you sure?' } %></button>
  </div>
<% end %>
<button class="button1" align="center"><%= link_to 'Create a New User', new_user_path %></button>
<br/>
<br/>
<br/>
<h2 class="h2profile2">  Manage Events: </h2>
<% @todos_eventos.each do |x| %>
  <div class="divorganization">
    <% unless x.banner_picture.attached? == true%>
      <span class="imageleft"><%= link_to image_tag("xd.jpeg") %></span>
    <% end %>
    <% unless x.banner_picture.attached?  == false%>
      <span class="imageleft"><%= link_to image_tag(url_for(x.banner_picture)) %></span>
    <% end %>
    <h4 class="organizationh4-1p"><%= x.title %></h4>
    <h4 class="organizationh4-1"><%= x.description %></h4>
    <h4 class="organizationh4-1"><%= x.location %></h4>
    <h4 class="organizationh4-1"><%= x.final_date %></h4>
    <button class="btn info"><%= link_to 'Show', event_path(x) %></button>
    <button class="btn warning"><%= link_to 'Edit', edit_event_path(x) %></button>
    <button class="btn danger"><%= link_to 'Delete', x ,method: :delete, data: { confirm: 'Are you sure?' } %></button>
  </div>
<% end %>
<button class="button1" align="center"><%= link_to 'Create a New Event', new_event_path %></button>
<br/>
<br/>
<br/>
<h2 class="h2profile2">  Manage Organizations: </h2>
<% @todos_organizaciones.each do |x| %>
  <div class="divorganization">
    <% unless x.banner_org.attached? == true%>
      <span class="imageleft"><%= link_to image_tag("xd.jpeg", width: '300px') %></span>
    <% end %>
    <% unless x.banner_org.attached?  == false%>
      <span class="imageleft"><%= link_to image_tag(url_for(x.banner_org), width: '300px') %></span>
    <% end %>
    <br/>
    <br/>
    <br/>
    <br/>
    <h4 class="organizationh4-1p"><%= x.name %></h4>
    <h4 class="organizationh4-1"><%= x.description %></h4>
    <br/>
    <br/>
    <button class="btn info"><%= link_to 'View', organization_path(x) %></button>
    <button class="btn warning"><%= link_to 'Edit', edit_organization_path(x) %></button>
    <button class="btn danger"><%= link_to 'Delete', x, method: :delete, data: { confirm: 'Are you sure?' } %></button>
  </div>
<% end %>
<button class="button1" align="center"><%= link_to 'Create a New Organization', new_organization_path %></button>

app/views/admin_manages/new.html.erb
<h1>New Admin Manage</h1>

<%= render 'form', admin_manage: @admin_manage %>

<%= link_to 'Back', admin_manages_path %>

app/views/admin_manages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_manage_path(@admin_manage) %> |
<%= link_to 'Back', admin_manages_path %>